### ISSUE TITLE
Fixnum is deprecated

### ISSUE THREAD

**Issue by danialbehzadi** [aziz/jalalidate#14]
I get these warnings on serving my Jekyll weblog:

    /…/vendor/ruby/2.5.0/gems/jalalidate-0.3.3/lib/jalalidate.rb:86: warning: constant ::Fixnum is deprecated
    /…/vendor/ruby/2.5.0/gems/jalalidate-0.3.3/lib/jalalidate.rb:87: warning: constant ::Fixnum is deprecated
    /…/vendor/ruby/2.5.0/gems/jalalidate-0.3.3/lib/jalalidate.rb:88: warning: constant ::Fixnum is deprecated

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
مطمئنی که داری از آخرین نسخه استفاده می‌کنی؟ به گمونم این رو قبلا درست کردیم. 
</div>

**Comment by danialbehzadi** [comment]
درسته. مشکل از من بود. با به‌روز رسانی درست شد. ممنون
