### ISSUE TITLE
Documentation ? 

### ISSUE THREAD

**Issue by misaghshakeri** [aziz/jalalidate#8]
It would be great if we can have at least one example of how to use this gem ?

**Comment by aziz** [comment]
@misaghshakeri The gem is documented using rdoc meaning the documentation is inline with the code and you can generate an HTML version of it using the `rdoc` gem.

There are multiple ways of accessing the HTML version of the docs.

1. clone the repo and run `rdoc .` inside the directory of this project
2. run `gem server`. find the gem name and click on the `[rdoc]` link.
